# These are supported funding model platforms

github: Rabbi DUSHIMIMANA, Aline Sonia, Kelly Designer, Gaston HAGENIMANA.
patreon: Omar 
open_collective: DEVOMA, AgriHub
ko_fi: AgriComercial
tidelift: npm or yarn
community_bridge: web and mobile app
liberapay: flask
issuehunt: MBONOMA
lfx_crowdfunding: MATSATSA
polar: ZONTRO
buy_me_a_coffee: VEVO
thanks_dev: OMAR
custom: https://www.linkedin.com/in/omar-mbonabucya-608375380/, https://www.instagram.com/0mar_rw/,
